### ISSUE TITLE
print summary of failed tests at the end

### ISSUE THREAD

**Issue by warmuuh** [scalatest/scalatest-maven-plugin#21]
It would be nice if we can see a summary of failed tests at the end of a run, 
otherwise if we have 1000 tests and one fails, i never know, which actually failed.
this would also be similar to the surefire plugin

**Comment by warmuuh** [comment]
found the ability to add custom reporters, should read the docs

**Comment by joedj** [comment]
For anyone else who stumbles on this issue while looking for a solution, you can add stdout reporter options to the maven config like `<stdout>T</stdout>`.
