### ISSUE TITLE
Release latest build to Maven Central

### ISSUE THREAD

**Issue by ryanb93** [scalatest/scalatest-maven-plugin#36]
Lots of changes have been merged in the last few days but the latest version in Maven is from Jun, 2014. Can we get a new official build published?

https://mvnrepository.com/artifact/org.scalatest/scalatest-maven-plugin

**Comment by patelh** [comment]
+1

**Comment by gcberger** [comment]
We have published a 2.0.0-SNAPSHOT release. If you have time please try it out and let us know if it works for you. Once (if) we get some positive responses, we'll release 2.0.0.

**Comment by patelh** [comment]
Please release a RC if you don't want to call it final.  But need a release to even test.

**Comment by patelh** [comment]
2.0-RC1 would be nice.

**Comment by adamdec** [comment]
So far so good with configuration:
`
                <plugin>
                    <groupId>org.scalatest</groupId>
                    <artifactId>scalatest-maven-plugin</artifactId>
                    <version>${maven.scalatest.plugin.version}</version>
                    <configuration>
                        <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
                        <junitxml>.</junitxml>
                        <filereports>WDF TestSuite.txt</filereports>
                    </configuration>
                    <executions>
                        <execution>
                            <id>test</id>
                            <goals>
                                <goal>test</goal>
                            </goals>
                            <configuration>
                                <suffixes>(?&lt;!Integration)(Test|Spec)</suffixes>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
`
on xubuntu 16.04

I am not using Windows anymore so someone else needs to test it on windows OS

**Comment by ryanb93** [comment]
@gcberger where was this released? Don't see it in maven central to be able to test it.

**Comment by patelh** [comment]
Can you guys do a release please?

**Comment by nikola-da** [comment]
@gcberger it has been 5 months since this issue was open. Sorry for sounding so blunt, but either there were not enough responses, because no one wants to test snapshot versions of plugins, or no one is using the plugin (which is not true). Please release 2.0.0 and then let people play with it. It is easy to make 2.0.x releases.

**Comment by bvenners** [comment]
Sorry for the delay in a release. We'll try and do a release this week.

**Comment by filfreire** [comment]
@bvenners any news on the release?

Btw created issue #47 that I think is of interest.

**Comment by bvenners** [comment]
Sorry for the delay. I made a ticket for making the release so we don't drop it again:

https://github.com/scalatest/scalatest-maven-plugin/issues/48

**Comment by bvenners** [comment]
At long last, 2.0.0 is released!

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest-maven-plugin/2.0.0/

Let me know if you have any trouble with this release.
