### ISSUE TITLE
Publish latest master to public maven repo please

### ISSUE THREAD

**Issue by patelh** [scalatest/scalatest-maven-plugin#41]
Please push all the fixes out to public repo.  The latest I see is 1.0 and that is from 2014.

**Comment by cstroe** [comment]
@patelh This issue is a duplicate of #36.  The maintainers have said they're working on it, please see this comment: https://github.com/scalatest/scalatest-maven-plugin/issues/27#issuecomment-303138538

As such, can you please close this issue?
