### ISSUE TITLE
scalatest threadsafe?

### ISSUE THREAD

**Issue by FelixReuthlingerBMW** [scalatest/scalatest-maven-plugin#57]
We are currently using scalatest in Maven with a parallel build, this will lead to Maven warning about threadsafety:

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in labeler:
[WARNING] org.scalatest:scalatest-maven-plugin:2.0.0
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************

Did anyone already experiment with this in multithreaded build (e.g. using -T1C option with mvn)? Or can we simply ignore this warning?

**Comment by janhicken** [comment]
I'm using the plugin for several parallel builds without issues. Maybe we should just add the annotation?

**Comment by Zejnilovic** [comment]
I would love this solved as well. It is not like it is generating errors or anything, but the warning bugs me.

**Comment by dominikjungo** [comment]
Is it possible to build a new release including this feature? As far as I see, 2.0.0 does not include it and 2.0.1 exists only as a SNAPSHOT.

**Comment by katrinsharp** [comment]
> Is it possible to build a new release including this feature? As far as I see, 2.0.0 does not include it and 2.0.1 exists only as a SNAPSHOT.

Yes. On it.
