### ISSUE TITLE
testNGConfigFiles not working

### ISSUE THREAD

**Issue by sashaostr** [scalatest/scalatest-maven-plugin#7]
testNGConfigFiles parameter goes to the wrong place - it passes to the org.scalatest.tools.Runner to 
-t param instead -b as said in http://www.scalatest.org/user_guide/using_the_runner#selectingSuitesAndTests.
I tried to run the Runner directly changing plugin call to the Runner from -t to -b and it works.
Thanks!

**Comment by ganeshm25** [comment]
I am trying to get scalatest maven plugin working with testngxml.
in my project testng xml is at /src/test/resources/testng.xml
here is what my scala plugin snippet:
            <plugin>
                <groupId>org.scalatest</groupId>
                <artifactId>scalatest-maven-plugin</artifactId>
                <version>${scalatest-maven-plugin.version}</version>
                <configuration>
                    <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
                    <junitxml>.</junitxml>
                    <filereports>test-suite.txt</filereports>
                </configuration>
                <executions>
                    <execution>
                        <id>test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <testNGConfigFiles>testng_smoke.xml</testNGConfigFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

**Comment by cheeseng** [comment]
@sashaostr @bvenners The changes seems to be in master branch already, I think we can close this old issue.
