### ISSUE TITLE
how to set  `<environmentVariables>` 

### ISSUE THREAD

**Issue by xhudik** [scalatest/scalatest-maven-plugin#84]
Hi there,
I'm trying to include some environmental variables into my test:
```
<environmentVariables>DATADIR="../DDDDD"</environmentVariables>
```
However, I'm getting:
```
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of
mojo org.scalatest:scalatest-maven-plugin:2.0.2:test for parameter environmentVariables: 
Cannot assign configuration entry 'environmentVariables' with value 'DATADIR="../DDDDD"' of type java.lang.String to 
property of type java.util.Map
```

can you please help me how to add correctly `<environmentVariables>`, or `systemProperties`? Or a link to documentation (i could find any example)

**Comment by andreoss** [comment]
@xhudik Variable name should be a tag, like that
```
        <environmentVariables>
            <FOO>bar</FOO>
        </environmentVariables>
```

**Comment by xhudik** [comment]
indeed - it is working! great thank you @andreoss . Just out of curiosity - where did you find how to use it? (i couldnt google it anywhere)

**Comment by andreoss** [comment]
@andreoss It's being parsed to `Map` here https://github.com/scalatest/scalatest-maven-plugin/blob/master/src/main/java/org/scalatest/tools/maven/AbstractScalaTestMojo.java#L266. Usually it means xml like above.
